export const updates_object_init = {
  companyName: "",
  clientName: "",
  jobHolder: "",
  department: "",
  source: "",
  brand: "",
  lead_Source: "",
  followUpDate: "",
  JobDate: "",
  Note: "",
  stage: "",
  status: "",
  value: "",
  number: "",
};
