// utils/leadFields.js
// Whitelist of selectable fields — never trust the `fields` query param directly,
// since it becomes a raw Mongo projection/sort key.
export const LEAD_ALLOWED_FIELDS = [
  "companyName",
  "clientName",
  "jobHolder",
  "leadUser",
  "department",
  "source",
  "brand",
  "leadCreatedAt",
  "followUpDate",
  "JobDate",
  "Note",
  "stage",
  "status",
  "value",
  "number",
  "email",
  "yearEnd",
  "jobDeadline",
  "sent",
  "received",
  "createdBy",
  "wonAt",
  "wonBy",
  "lostAt",
  "lostBy",
  "lead_Source",
  "leadRef",
  "createdAt",
  "updatedAt",
];